name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fetch-depth: 0
      - name: go
        uses: actions/setup-go@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          go-version: 1.18
      - uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
